# Generated by Django 4.2.2 on 2023-06-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of Service', 'Out of Service')], default='Available', max_length=15),
        ),
    ]
